services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next.js-app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    working_dir: /app
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
